name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Example
      uses: echo "Hello World"

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ddukddak01/cicd-demo:latest

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ddukddak01/cicd-demo:latest
        format: table
        exit-code: 0
        vuln-type: 'os,library'

    - name: Run Gitleaks secret scan
      uses: gitleaks/gitleaks-action@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt pytest

    - name: Run pytest
      run: pytest tests/

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes with kubectl
      run: kubectl apply -f k8s/deployment.yaml

    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "CI/CD 완료: ${{ github.workflow }} - ${{ github.ref }} by ${{ github.actor }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ CI/CD Pipeline Success"
        body: |
          Workflow: ${{ github.workflow }}
          Ref: ${{ github.ref }}
          Actor: ${{ github.actor }}
          Status: Success
        to: netadmin@example.com
        from: ${{ secrets.EMAIL_USERNAME }}
