name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t demo-app .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: demo-app
        format: table
        exit-code: 1     # 취약점 있으면 실패 처리 (데모용 강조 가능)
        ignore-unfixed: true
        vuln-type: 'os,library'
